# Site settings
title: Jake Larkin
email: jake@jakelarkin.co
description: > # this means to ignore newlines until "baseurl:"
  This is Jake Larkin's personal website and blog.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jakelarkin.co" # the base hostname & protocol for your site
twitter_username: jakelarkin71
github_username:  larkin.71

# Build settings
markdown: kramdown
